---
title: "The Qualitative Report"
author: "Jordi López"
date: 2015-07-23T21:13:14-05:00
categories: ["Revistas"]
tags: ["open access"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# [The Qualitative Report (ISSN 1052-0147)](https://nsuworks.nova.edu/tqr/)

The Qualitative Report (ISSN 1052-0147) is a peer-reviewed, on-line monthly journal devoted to writing and discussion of and about qualitative, critical, action, and collaborative inquiry and research. The Qualitative Report, the oldest multidisciplinary qualitative research journal in the world, serves as a forum and sounding board for researchers, scholars, practitioners, and other reflective-minded individuals who are passionate about ideas, methods, and analyses permeating qualitative, action, collaborative, and critical study. These pages are open to a variety of forms: original, scholarly activity such as qualitative research studies, critical commentaries, editorials, or debates concerning pertinent issues and topics; news of networking and research possibilities; and other sorts of journalistic and literary shapes which may interest and pique readers.


